Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'spec/spec_helper.rb'
    - 'test/spec_helper.rb'
#    - 'spec/teaspoon_env.rb'
    - 'vendor/**/*'
    - 'lib/tasks/display-coverage.rake'
    - 'config.ru'
    - 'Rakefile'
    - 'lib/tasks/*.rake'

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
